package com.example.gramasanjeevin.utils

import java.util.Locale

object L {
    fun s(isEnglish: Boolean, en: String, kn: String): String {
        return if (isEnglish) en else kn
    }

    // Common
    fun gramaSanjeevini(isEng: Boolean) = s(isEng, "Grama-Sanjeevini", "ಗ್ರಾಮ-ಸಂಜೀವಿನಿ")
    fun back(isEng: Boolean) = s(isEng, "Back", "ಹಿಂದಕ್ಕೆ")
    fun logout(isEng: Boolean) = s(isEng, "Logout", "ನಿರ್ಗಮಿಸಿ")
    fun cancel(isEng: Boolean) = s(isEng, "Cancel", "ರದ್ದುಮಾಡಿ")
    fun confirm(isEng: Boolean) = s(isEng, "Confirm", "ದೃಢೀಕರಿಸಿ")
    fun loading(isEng: Boolean) = s(isEng, "Loading...", "ಲೋಡ್ ಆಗುತ್ತಿದೆ...")
    fun close(isEng: Boolean) = s(isEng, "Close", "ಮುಚ್ಚಿ")
    fun warning(isEng: Boolean) = s(isEng, "Warning", "ಎಚ್ಚರಿಕೆ")
    fun search(isEng: Boolean) = s(isEng, "Search", "ಹುಡುಕಿ")
    fun items(isEng: Boolean) = s(isEng, "Items", "ವಸ್ತುಗಳು")
    fun status(isEng: Boolean) = s(isEng, "Status", "ಸ್ಥಿತಿ")
    fun help(isEng: Boolean) = s(isEng, "Help", "ಸಹಾಯ")
    fun fromLabel(isEng: Boolean) = s(isEng, "From:", "ಇಂದ:")
    fun errorLabel(isEng: Boolean) = s(isEng, "Error", "ದೋಷ")
    fun orLabel(isEng: Boolean) = s(isEng, " OR ", " ಅಥವಾ ")
    fun units(isEng: Boolean) = s(isEng, "Units", "ಘಟಕಗಳು")

    // Status Values
    fun statusPending(isEng: Boolean) = s(isEng, "PENDING", "ಬಾಕಿ ಇದೆ")
    fun statusApproved(isEng: Boolean) = s(isEng, "APPROVED", "ಅನುಮೋದಿಸಲಾಗಿದೆ")
    fun statusCompleted(isEng: Boolean) = s(isEng, "COMPLETED", "ಪೂರ್ಣಗೊಂಡಿದೆ")
    fun statusRejected(isEng: Boolean) = s(isEng, "REJECTED", "ತಿರಸ್ಕರಿಸಲಾಗಿದೆ")
    fun statusReviewed(isEng: Boolean) = s(isEng, "REVIEWED", "ಪರಿಶೀಲಿಸಲಾಗಿದೆ")
    fun waitingForApproval(isEng: Boolean) = s(isEng, "Waiting for approval", "ಅನುಮೋದನೆಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ")
    fun deliveryApproved(isEng: Boolean) = s(isEng, "Delivery approved", "ವಿತರಣೆ ಅನುಮೋದಿಸಲಾಗಿದೆ")
    fun restockApproved(isEng: Boolean) = s(isEng, "Re-stock approved", "ಮರುಪೂರಣ ಅನುಮೋದಿಸಲಾಗಿದೆ")
    fun reviewInProgress(isEng: Boolean) = s(isEng, "Review in progress", "ಪರಿಶೀಲನೆ ನಡೆಯುತ್ತಿದೆ")

    // Login Screen
    fun welcomeBack(isEng: Boolean) = s(isEng, "Welcome Back", "ಸ್ವಾಗತ")
    fun selectRole(isEng: Boolean) = s(isEng, "Please select your role to continue", "ಮುಂದುವರಿಯಲು ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ")
    fun villager(isEng: Boolean) = s(isEng, "Villager", "ಗ್ರಾಮಸ್ಥರು")
    fun villagerSub(isEng: Boolean) = s(isEng, "Access healthcare services", "ಆರೋಗ್ಯ ಸೇವೆಗಳನ್ನು ಪಡೆಯಿರಿ")
    fun pharmacist(isEng: Boolean) = s(isEng, "Pharmacist", "ಔಷಧಿಕಾರರು")
    fun pharmacistSub(isEng: Boolean) = s(isEng, "Manage inventory & requests", "ದಾಸ್ತಾನು ಮತ್ತು ವಿನಂತಿಗಳನ್ನು ನಿರ್ವಹಿಸಿ")
    fun email(isEng: Boolean) = s(isEng, "Email Address", "ಇಮೇಲ್ ವಿಳಾಸ")
    fun password(isEng: Boolean) = s(isEng, "Password", "ಪಾಸ್‌ವರ್ಡ್")
    fun signIn(isEng: Boolean) = s(isEng, "Sign In", "ಲಾಗಿನ್")
    fun signUp(isEng: Boolean) = s(isEng, "Sign Up", "ನೋಂದಾಯಿಸಿ")
    fun dontHaveAccount(isEng: Boolean) = s(isEng, "Don't have an account? Sign Up", "ಖಾತೆ ಇಲ್ಲವೇ? ನೋಂದಾಯಿಸಿ")
    fun alreadyHaveAccount(isEng: Boolean) = s(isEng, "Already have an account? Sign In", "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ")
    fun googleContinue(isEng: Boolean) = s(isEng, "Continue with Google", "Google ಮೂಲಕ ಮುಂದುವರಿಯಿರಿ")
    fun fullName(isEng: Boolean) = s(isEng, "Full Name", "ಪೂರ್ಣ ಹೆಸರು")
    fun yourHealthPriority(isEng: Boolean) = s(isEng, "Your Health, Our Priority", "ನಿಮ್ಮ ಆರೋಗ್ಯ, ನಮ್ಮ ಆದ್ಯತೆ")
    fun authSecured(isEng: Boolean) = s(isEng, "Secured by Grama-Sanjeevini Auth", "ಗ್ರಾಮ-ಸಂಜೀವಿನಿ ದೃಢೀಕರಣದಿಂದ ಸುರಕ್ಷಿತವಾಗಿದೆ")
    fun termsPrivacy(isEng: Boolean) = s(isEng, "Terms & Privacy Policy", "ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತೆ ನೀತಿ")
    fun authStepSubTitle(isEng: Boolean, isSignUp: Boolean) = if (isSignUp)
        s(isEng, "Create an account to get started", "ಪ್ರಾರಂಭಿಸಲು ಖಾತೆಯನ್ನು ರಚಿಸಿ")
    else
        s(isEng, "Sign in to continue to your dashboard", "ಮುಂದುವರಿಯಲು ಸೈನ್ ಇನ್ ಮಾಡಿ")

    // Home Screen
    fun ruralFinder(isEng: Boolean) = s(isEng, "Rural Medicine Finder", "ಗ್ರಾಮೀಣ ಔಷಧ ಶೋಧಕ")
    fun searchMedicine(isEng: Boolean) = s(isEng, "Search Medicine", "ಔಷಧ ಹುಡುಕಿ")
    fun searchMedicineSub(isEng: Boolean) = s(isEng, "Check availability in local pharmacies", "ಸ್ಥಳೀಯ ಫಾರ್ಮಸಿಗಳಲ್ಲಿ ಲಭ್ಯತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ")
    fun lifeSaving(isEng: Boolean) = s(isEng, "Life Saving Drugs", "ಜೀವ ಉಳಿಸುವ ಔಷಧಗಳು")
    fun lifeSavingSub(isEng: Boolean) = s(isEng, "Emergency inventory & critical supplies", "ತುರ್ತು ದಾಸ್ತಾನು ಮತ್ತು ನಿರ್ಣಾಯಕ ಪೂರೈಕೆಗಳು")
    fun nearbyHubs(isEng: Boolean) = s(isEng, "Nearby Hubs", "ಹತ್ತಿರದ ಕೇಂದ್ರಗಳು")
    fun alertLevel(isEng: Boolean) = s(isEng, "Alert Level", "ಎಚ್ಚರಿಕೆ ಮಟ್ಟ")
    fun normal(isEng: Boolean) = s(isEng, "Normal", "ಸಾಮಾನ್ಯ")
    fun emergencySupport(isEng: Boolean) = s(isEng, "Emergency Support", "ತುರ್ತು ಸಹಾಯ")
    fun helpline(isEng: Boolean) = s(isEng, "24/7 Helpline", "24/7 ಸಹಾಯವಾಣಿ")
    fun firstAid(isEng: Boolean) = s(isEng, "First-Aid Basics", "ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ")
    fun needHelp(isEng: Boolean) = s(isEng, "Need More Help?", "ಹೆಚ್ಚಿನ ಸಹಾಯ ಬೇಕೇ?")
    fun contactHub(isEng: Boolean) = s(isEng, "Contact your local hub for any queries.", "ಯಾವುದೇ ಪ್ರಶ್ನೆಗಳಿಗಾಗಿ ನಿಮ್ಮ ಸ್ಥಳೀಯ ಕೇಂದ್ರವನ್ನು ಸಂಪರ್ಕಿಸಿ.")
    fun needAssistance(isEng: Boolean) = s(isEng, "Need Assistance?", "ಸಹಾಯ ಬೇಕೇ?")
    fun callWorker(isEng: Boolean) = s(isEng, "Call your community healthcare worker directly from the app.", "ಅಪ್ಲಿಕೇಶನ್‌ನಿಂದ ನೇರವಾಗಿ ನಿಮ್ಮ ಸಮುದಾಯ ಆರೋಗ್ಯ ಕಾರ್ಯಕರ್ತರಿಗೆ ಕರೆ ಮಾಡಿ.")
    fun slide1(isEng: Boolean) = s(isEng, "Ensuring health for every village.", "ಪ್ರತಿ ಗ್ರಾಮಕ್ಕೂ ಆರೋಗ್ಯವನ್ನು ಖಚಿತಪಡಿಸುವುದು.")
    fun slide2(isEng: Boolean) = s(isEng, "24/7 Access to Life Saving Drugs.", "ಜೀವ ಉಳಿಸುವ ಔಷಧಗಳಿಗೆ 24/7 ಪ್ರವೇಶ.")
    fun slide3(isEng: Boolean) = s(isEng, "Bridging the Gap in Rural Healthcare.", "ಗ್ರಾಮೀಣ ಆರೋಗ್ಯ ರಕ್ಷಣೆಯಲ್ಲಿನ ಅಂತರವನ್ನು ಕಡಿಮೆ ಮಾಡುವುದು.")

    // Nav Bar
    fun home(isEng: Boolean) = s(isEng, "Home", "ಮನೆ")
    fun cart(isEng: Boolean) = s(isEng, "Cart", "ಕಾರ್ಟ್")
    fun alerts(isEng: Boolean) = s(isEng, "Alerts", "ಎಚ್ಚರಿಕೆಗಳು")
    fun profile(isEng: Boolean) = s(isEng, "Profile", "ಪ್ರೊಫೈಲ್")
    fun dashboard(isEng: Boolean) = s(isEng, "Dashboard", "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್")
    fun requests(isEng: Boolean) = s(isEng, "Requests", "ವಿನಂತಿಗಳು")

    // Profile Screen
    fun editProfile(isEng: Boolean) = s(isEng, "Edit Profile", "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ")
    fun saveChanges(isEng: Boolean) = s(isEng, "Save Changes", "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ")
    fun language(isEng: Boolean) = s(isEng, "Language", "ಭಾಷೆ")
    fun phoneNumber(isEng: Boolean) = s(isEng, "Phone Number", "ದೂರವಾಣಿ ಸಂಖ್ಯೆ")
    fun village(isEng: Boolean) = s(isEng, "Village", "ಗ್ರಾಮ")
    fun healthId(isEng: Boolean) = s(isEng, "Health ID (ABHA)", "ಆರೋಗ್ಯ ಐಡಿ (ABHA)")
    fun address(isEng: Boolean) = s(isEng, "Full Address", "ಪೂರ್ಣ ವಿಳಾಸ")
    fun unknownUser(isEng: Boolean) = s(isEng, "Unknown User", "ಅಪರಿಚಿತ ಬಳಕೆದಾರ")
    fun unknownVillage(isEng: Boolean) = s(isEng, "Unknown Village", "ಅಪರಿಚಿತ ಗ್ರಾಮ")
    fun notSet(isEng: Boolean) = s(isEng, "Not set", "ಹೊಂದಿಸಿಲ್ಲ")
    fun profileUpdated(isEng: Boolean) = s(isEng, "Profile Updated Successfully!", "ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!")

    // Alerts Screen
    fun myAlertsStatus(isEng: Boolean) = s(isEng, "My Alerts & Status", "ನನ್ನ ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ಸ್ಥಿತಿ")
    fun noActivityYet(isEng: Boolean) = s(isEng, "No activity yet", "ಇನ್ನೂ ಯಾವುದೇ ಚಟುವಟಿಕೆ ಇಲ್ಲ")
    fun alertsEmptySub(isEng: Boolean) = s(isEng, "Your delivery or restock requests will appear here with real-time status updates.", "ನಿಮ್ಮ ವಿತರಣೆ ಅಥವಾ ಮರುಪೂರಣ ವಿನಂತಿಗಳು ಇಲ್ಲಿ ನೈಜ-ಸಮಯದ ಸ್ಥಿತಿ ಅಪ್‌ಡೇಟ್‌ಗಳೊಂದಿಗೆ ಗೋಚರಿಸುತ್ತವೆ.")
    fun withdrawRequest(isEng: Boolean) = s(isEng, "Withdraw Request", "ವಿನಂತಿ ಹಿಂಪಡೆಯಿರಿ")
    fun requestWithdrawnSuccess(isEng: Boolean) = s(isEng, "Request withdrawn successfully", "ವಿನಂತಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಹಿಂಪಡೆಯಲಾಗಿದೆ")
    fun failedToWithdraw(isEng: Boolean) = s(isEng, "Failed to withdraw", "ಹಿಂಪಡೆಯಲು ವಿಫಲವಾಗಿದೆ")
    fun justNow(isEng: Boolean) = s(isEng, "Just now", "ಈಗ ತಾನೇ")

    // Hubs Screen
    fun nearestMedicalHubs(isEng: Boolean) = s(isEng, "Nearest Medical Hubs", "ಹತ್ತಿರದ ವೈದ್ಯಕೀಯ ಕೇಂದ್ರಗಳು")

    // Cart Screen
    fun smartMatches(isEng: Boolean) = s(isEng, "Smart Cart Matches", "ಸ್ಮಾರ್ಟ್ ಕಾರ್ಟ್ ಹೊಂದಾಣಿಕೆಗಳು")
    fun smartMatchesSub(isEng: Boolean, count: Int) = s(isEng, "Find the best pharmacy options for your $count needed items.", "ನಿಮ್ಮ $count ಅಗತ್ಯ ವಸ್ತುಗಳಿಗಾಗಿ ಅತ್ಯುತ್ತಮ ಫಾರ್ಮಸಿ ಆಯ್ಕೆಗಳನ್ನು ಹುಡುಕಿ.")
    fun cartItemsHeader(isEng: Boolean) = s(isEng, "Items in Cart:", "ಕಾರ್ಟ್‌ನಲ್ಲಿರುವ ವಸ್ತುಗಳು:")
    fun scanPrescription(isEng: Boolean) = s(isEng, "Scan Prescription", "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ")
    fun uploadPrescription(isEng: Boolean) = s(isEng, "Upload Prescription", "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ")
    fun changePrescription(isEng: Boolean) = s(isEng, "Change Prescription", "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಬದಲಿಸಿ")
    fun getDirections(isEng: Boolean) = s(isEng, "Get Directions", "ನಕ್ಷೆ ನೋಡಿ")
    fun requestDelivery(isEng: Boolean) = s(isEng, "Request Home Delivery", "ಮನೆಗೆ ತಲುಪಿಸಲು ವಿನಂತಿಸಿ")
    fun requestRestock(isEng: Boolean) = s(isEng, "Request Restock", "ದಾಸ್ತಾನು ವಿನಂತಿಸಿ")
    fun prescriptionAttached(isEng: Boolean) = s(isEng, "Prescription Attached", "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಲಗತ್ತಿಸಲಾಗಿದೆ")
    fun sharedWithPharmacist(isEng: Boolean) = s(isEng, "Shared with Pharmacist", "ಫಾರ್ಮಾಸಿಸ್ಟ್‌ಗೆ ಹಂಚಿಕೊಳ್ಳಲಾಗಿದೆ")
    fun emptyCart(isEng: Boolean) = s(isEng, "Your cart is empty", "ನಿಮ್ಮ ಕಾರ್ಟ್ ಖಾಲಿ ಇದೆ")
    fun emptyCartSub(isEng: Boolean) = s(isEng, "Add medicines to see smart matches.", "ಸ್ಮಾರ್ಟ್ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ನೋಡಲು ಔಷಧಗಳನ್ನು ಸೇರಿಸಿ.")
    fun goToSearch(isEng: Boolean) = s(isEng, "Go to Search", "ಹುಡುಕಾಟಕ್ಕೆ ಹೋಗಿ")
    fun prescriptionWarning(isEng: Boolean) = s(isEng, "Warning: The medicines in your cart cannot be provided without a valid prescription.", "ಎಚ್ಚರಿಕೆ: ಮಾನ್ಯವಾದ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಇಲ್ಲದೆ ನಿಮ್ಮ ಕಾರ್ಟ್‌ನಲ್ಲಿರುವ ಔಷಧಗಳನ್ನು ನೀಡಲಾಗುವುದಿಲ್ಲ.")
    fun completeMatches(isEng: Boolean) = s(isEng, "COMPLETE MATCHES (ALL ITEMS)", "ಪೂರ್ಣ ಹೊಂದಾಣಿಕೆಗಳು (ಎಲ್ಲಾ ವಸ್ತುಗಳು)")
    fun partialMatches(isEng: Boolean) = s(isEng, "PARTIAL MATCHES", "ಭಾಗಶಃ ಹೊಂದಾಣಿಕೆಗಳು")
    fun noMatchesFound(isEng: Boolean) = s(isEng, "No matching pharmacies found for these items.", "ಈ ವಸ್ತುಗಳಿಗೆ ಯಾವುದೇ ಹೊಂದಾಣಿಕೆಯ ಫಾರ್ಮಸಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ.")
    fun autoFilled(isEng: Boolean) = s(isEng, "Auto-filled", "ಸ್ವಯಂ-ಭರ್ತಿ")
    fun uploadPrescriptionToUnlock(isEng: Boolean) = s(isEng, "Upload Prescription to Unlock", "ಅನ್ಲಾಕ್ ಮಾಡಲು ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ")

    // Prescription Scanner
    fun aiScannerTitle(isEng: Boolean) = s(isEng, "AI Prescription Scanner", "AI ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಸ್ಕ್ಯಾನರ್")
    fun aiScanning(isEng: Boolean) = s(isEng, "AI scanning prescription...", "AI ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಸ್ಕ್ಯಾನ್ ಮಾಡುತ್ತಿದೆ...")
    fun takePhoto(isEng: Boolean) = s(isEng, "Take Photo", "ಫೋಟೋ ತೆಗೆಯಿರಿ")
    fun gallery(isEng: Boolean) = s(isEng, "Gallery", "ಗ್ಯಾಲರಿ")
    fun extractedMedicines(isEng: Boolean) = s(isEng, "AI Extracted Medicines:", "AI ಪಡೆದ ಔಷಧಗಳು:")
    fun aiFoundAdded(isEng: Boolean, count: Int) = s(isEng, "AI found and added $count medicines to your cart!", "AI $count ಔಷಧಗಳನ್ನು ಹುಡುಕಿ ನಿಮ್ಮ ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿದೆ!")
    fun prescriptionConsent(isEng: Boolean) = s(isEng, "The selected/uploaded images of your prescription will be shared with the pharmacist and admin.", "ಆಯ್ಕೆಮಾಡಿದ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಚಿತ್ರಗಳನ್ನು ಫಾರ್ಮಾಸಿಸ್ಟ್ ಮತ್ತು ನಿರ್ವಾಹಕರೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಲಾಗುತ್ತದೆ.")
    fun confirmContinueCart(isEng: Boolean) = s(isEng, "Confirm & Continue to Cart", "ಖಚಿತಪಡಿಸಿ ಮತ್ತು ಕಾರ್ಟ್‌ಗೆ ಮುಂದುವರಿಯಿರಿ")
    fun uploadingPrescription(isEng: Boolean) = s(isEng, "Uploading Prescription...", "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...")
    fun ocrNoMedicines(isEng: Boolean) = s(isEng, "No medicines found. Please try a clearer image.", "ಯಾವುದೇ ಔಷಧಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ದಯವಿಟ್ಟು ಸ್ಪಷ್ಟ ಚಿತ್ರವನ್ನು ಪ್ರಯತ್ನಿಸಿ.")
    fun ocrCrossReferencing(isEng: Boolean) = s(isEng, "Cross-referencing with database...", "ಡೇಟಾಬೇಸ್‌ನೊಂದಿಗೆ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...")
    fun ocrSuccessfullyExtracted(isEng: Boolean, items: String) = s(isEng, "Successfully extracted and added: $items", "ಯಶಸ್ವಿಯಾಗಿ ಪಡೆದು ಸೇರಿಸಲಾಗಿದೆ: $items")
    fun ocrNoMatches(isEng: Boolean, items: String) = s(isEng, "Extracted: $items\n(No matching items in our database)", "ಪಡೆಯಲಾಗಿದೆ: $items\n(ನಮ್ಮ ಡೇಟಾಬೇಸ್‌ನಲ್ಲಿ ಯಾವುದೇ ಹೊಂದಾಣಿಕೆಯ ವಸ್ತುಗಳಿಲ್ಲ)")
    fun noImageSelected(isEng: Boolean) = s(isEng, "No image selected", "ಚಿತ್ರವನ್ನು ಆಯ್ಕೆ ಮಾಡಿಲ್ಲ")

    // Emergency Screen
    fun lifeSavingMedicines(isEng: Boolean) = s(isEng, "Life Saving Medicines", "ಜೀವ ಉಳಿಸುವ ಔಷಧಗಳು")
    fun emergencySub(isEng: Boolean) = s(isEng, "Urgent medical supplies available in your immediate vicinity. Every second counts.", "ನಿಮ್ಮ ಹತ್ತಿರದ ಪ್ರದೇಶದಲ್ಲಿ ಲಭ್ಯವಿರುವ ತುರ್ತು ವೈದ್ಯಕೀಯ ಸರಬರಾಜುಗಳು. ಪ್ರತಿ ಸೆಕೆಂಡ್ ಮುಖ್ಯ.")
    fun searchCritical(isEng: Boolean) = s(isEng, "Search critical medicine...", "ನಿರ್ಣಾಯಕ ಔಷಧ ಹುಡುಕಿ...")
    fun firstAidTips(isEng: Boolean) = s(isEng, "First-Aid Tips", "ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ ಸಲಹೆಗಳು")
    fun distanceAway(isEng: Boolean, dist: Double) = s(isEng, String.format(Locale.US, "%.1f km away", dist), String.format(Locale.US, "%.1f ಕಿಮೀ ದೂರದಲ್ಲಿದೆ", dist))
    fun qtyLabel(isEng: Boolean, qty: Int) = s(isEng, "Qty: $qty", "ಪ್ರಮಾಣ: $qty")
    fun outOfStock(isEng: Boolean) = s(isEng, "OUT OF STOCK", "ದಾಸ್ತಾನು ಇಲ್ಲ")
    fun restockRequestSent(isEng: Boolean) = s(isEng, "Restock request sent!", "ಮರುಪೂರಣ ವಿನಂತಿ ಕಳುಹಿಸಲಾಗಿದೆ!")

    // Search Screen
    fun findMedicine(isEng: Boolean) = s(isEng, "Find Medicine", "ಔಷಧ ಪತ್ತೆಹಚ್ಚಿ")
    fun searchMedicinePlaceholder(isEng: Boolean) = s(isEng, "Search for a medicine...", "ಔಷಧಿಗಾಗಿ ಹುಡುಕಿ...")
    fun popularInArea(isEng: Boolean) = s(isEng, "Popular in your area", "ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ ಜನಪ್ರಿಯ")
    fun healthResources(isEng: Boolean) = s(isEng, "Health Resources", "ಆರೋಗ್ಯ ಸಂಪನ್ಮೂಲಗಳು")
    fun addToCart(isEng: Boolean) = s(isEng, "Add to Cart", "ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ")
    fun addedToCart(isEng: Boolean, name: String) = s(isEng, "$name added to cart", "$name ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಲಾಗಿದೆ")
    fun noMedicinesFound(isEng: Boolean, query: String) = s(isEng, "No medicines found matching \"$query\"", "\"$query\" ಗೆ ಹೊಂದಿಕೆಯಾಗುವ ಯಾವುದೇ ಔಷಧಗಳು ಕಂಡುಬಂದಿಲ್ಲ")
    fun speakMedicineName(isEng: Boolean) = s(isEng, "Speak medicine name...", "ಔಷಧದ ಹೆಸರನ್ನು ಹೇಳಿ...")
    fun addLabel(isEng: Boolean) = s(isEng, "Add", "ಸೇರಿಸಿ")
    fun monsoonGuide(isEng: Boolean) = s(isEng, "Monsoon Health Guide", "ಮುಂಗಾರು ಆರೋಗ್ಯ ಮಾರ್ಗದರ್ಶಿ")

    // Pharmacist Dashboard
    fun pharmacyDashboard(isEng: Boolean) = s(isEng, "Pharmacy Dashboard", "ಫಾರ್ಮಸಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್")
    fun manageInventory(isEng: Boolean) = s(isEng, "Manage your store inventory", "ನಿಮ್ಮ ಅಂಗಡಿಯ ದಾಸ್ತಾನು ನಿರ್ವಹಿಸಿ")
    fun actionRequired(isEng: Boolean) = s(isEng, "Action Required", "ಕ್ರಮ ಅಗತ್ಯವಿದೆ")
    fun stockAlerts(isEng: Boolean) = s(isEng, "Stock Alerts", "ದಾಸ್ತಾನು ಎಚ್ಚರಿಕೆಗಳು")
    fun storeManagement(isEng: Boolean) = s(isEng, "Store Management", "ಅಂಗಡಿ ನಿರ್ವಹಣೆ")
    fun myInventory(isEng: Boolean) = s(isEng, "My Inventory", "ನನ್ನ ದಾಸ್ತಾನು")
    fun customerRequests(isEng: Boolean) = s(isEng, "Customer Requests", "ಗ್ರಾಹಕರ ವಿನಂತಿಗಳು")
    fun pharmacyVerification(isEng: Boolean) = s(isEng, "Pharmacy Verification", "ಫಾರ್ಮಸಿ ಪರಿಶೀಲನೆ")
    fun totalItems(isEng: Boolean) = s(isEng, "Total Items", "ಒಟ್ಟು ವಸ್ತುಗಳು")
    fun stockHealth(isEng: Boolean) = s(isEng, "Stock Health", "ದಾಸ್ತಾನು ಸ್ಥಿತಿ")
    fun itemsRequireAttention(isEng: Boolean, count: Int) = s(isEng, "$count items require immediate attention due to low stock or expiry.", "$count ವಸ್ತುಗಳಿಗೆ ಕಡಿಮೆ ದಾಸ್ತಾನು ಅಥವಾ ಅವಧಿ ಮುಕ್ತಾಯದ ಕಾರಣ ತಕ್ಷಣದ ಗಮನ ಅಗತ್ಯವಿದೆ.")

    // Pharmacist Inventory
    fun inventory(isEng: Boolean) = s(isEng, "Inventory", "ದಾಸ್ತಾನು")
    fun myInventoryHeader(isEng: Boolean, name: String) = s(isEng, "My Inventory - $name", "ನನ್ನ ದಾಸ್ತಾನು - $name")
    fun manageUpdateStock(isEng: Boolean) = s(isEng, "Manage and update medicine stock levels for rural distribution.", "ಗ್ರಾಮೀಣ ವಿತರಣೆಗಾಗಿ ಔಷಧ ದಾಸ್ತಾನು ಮಟ್ಟವನ್ನು ನಿರ್ವಹಿಸಿ ಮತ್ತು ನವೀಕರಿಸಿ.")
    fun addNew(isEng: Boolean) = s(isEng, "Add New", "ಹೊಸದನ್ನು ಸೇರಿಸಿ")
    fun updateStock(isEng: Boolean) = s(isEng, "Update Stock", "ದಾಸ್ತಾನು ನವೀಕರಿಸಿ")
    fun unitsLeft(isEng: Boolean) = s(isEng, "Units Left", "ಉಳಿದಿರುವ ಘಟಕಗಳು")
    fun expires(isEng: Boolean, date: String) = s(isEng, "Expires: $date", "ಅವಧಿ ಮುಗಿಯುವ ದಿನಾಂಕ: $date")
    fun outOfStockCaps(isEng: Boolean) = s(isEng, "OUT OF STOCK", "ದಾಸ್ತಾನು ಇಲ್ಲ")
    fun criticallyLow(isEng: Boolean) = s(isEng, "CRITICALLY LOW", "ಅತ್ಯಂತ ಕಡಿಮೆ ಇದೆ")
    fun expiringInDays(isEng: Boolean, days: Long) = s(isEng, "EXPIRING IN $days DAYS", "$days ದಿನಗಳಲ್ಲಿ ಅವಧಿ ಮುಗಿಯುತ್ತದೆ")
    fun updateStockHeader(isEng: Boolean, name: String) = s(isEng, "Update Stock:\n$name", "ದಾಸ್ತಾನು ನವೀಕರಿಸಿ:\n$name")
    fun adjustInventorySub(isEng: Boolean) = s(isEng, "Adjust the current inventory quantity and expiry for this medicine.", "ಈ ಔಷಧಕ್ಕಾಗಿ ಪ್ರಸ್ತುತ ದಾಸ್ತಾನು ಪ್ರಮಾಣ ಮತ್ತು ಅವಧಿ ಮುಕ್ತಾಯವನ್ನು ಹೊಂದಿಸಿ.")
    fun inventoryReportSuccess(isEng: Boolean) = s(isEng, "Inventory report generated successfully.", "ದಾಸ್ತಾನು ವರದಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸಿದ್ಧಪಡಿಸಲಾಗಿದೆ.")

    // Pharmacist Request & Review
    fun pendingRequests(isEng: Boolean, count: Int) = s(isEng, "$count new requests pending", "$count ಹೊಸ ವಿನಂತಿಗಳು ಬಾಕಿ ಇವೆ")
    fun noPendingRequests(isEng: Boolean) = s(isEng, "No pending requests", "ಯಾವುದೇ ಬಾಕಿ ವಿನಂತಿಗಳಿಲ್ಲ")
    fun approve(isEng: Boolean) = s(isEng, "Approve", "ಅನುಮೋದಿಸಿ")
    fun decline(isEng: Boolean) = s(isEng, "Decline", "ತಿರಸ್ಕರಿಸಿ")
    fun viewPrescription(isEng: Boolean) = s(isEng, "View Prescription", "ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ನೋಡಿ")
    fun reviewOrder(isEng: Boolean) = s(isEng, "Review Order", "ಆರ್ಡರ್ ಪರಿಶೀಲಿಸಿ")
    fun viewDetails(isEng: Boolean) = s(isEng, "View Details", "ವಿವರಗಳನ್ನು ನೋಡಿ")
    fun itemsInOrder(isEng: Boolean) = s(isEng, "Items in Order", "ಆರ್ಡರ್‌ನಲ್ಲಿರುವ ವಸ್ತುಗಳು")
    fun completeReview(isEng: Boolean) = s(isEng, "Complete Review", "ಪರಿಶೀಲನೆ ಪೂರ್ಣಗೊಳಿಸಿ")
    fun rejectItem(isEng: Boolean) = s(isEng, "Reject Item", "ವಸ್ತುವನ್ನು ತಿರಸ್ಕರಿಸಿ")
    fun provideRejectionReason(isEng: Boolean, name: String) = s(isEng, "Provide a reason for rejecting $name:", "$name ಅನ್ನು ತಿರಸ್ಕರಿಸಲು ಕಾರಣ ನೀಡಿ:")
    fun confirmReject(isEng: Boolean) = s(isEng, "Confirm Reject", "ತಿರಸ್ಕಾರವನ್ನು ಖಚಿತಪಡಿಸಿ")
    fun orderNotFound(isEng: Boolean) = s(isEng, "Order not found", "ಆರ್ಡರ್ ಕಂಡುಬಂದಿಲ್ಲ")
    fun noPrescriptionUploaded(isEng: Boolean) = s(isEng, "No prescription uploaded", "ಯಾವುದೇ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಿಲ್ಲ")
    fun aiAutofilled(isEng: Boolean) = s(isEng, "AI Auto-filled", "AI ಸ್ವಯಂ-ಭರ್ತಿ")
    fun reasonLabel(isEng: Boolean) = s(isEng, "Reason", "ಕಾರಣ")
    fun patientPrescription(isEng: Boolean) = s(isEng, "Patient Prescription", "ರೋಗಿಯ ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್")
}
